Repository p2plabsxyz/peersky-browser, pull requests merged in 2025-07, with the labels that each got.

#50 feat: add support for directory uploads via file input
  package-lock.json
  src/pages/p2p/upload/index.html
Labels: enhancement

#51 feat: Added Bookmarks feature in Peersky Browser.
  src/pages/404.html
  src/pages/bookmarks.html
  src/pages/nav-box.js
  src/pages/preload.js
  src/pages/static/assets/svg/bookmark-fill.svg
  src/pages/static/assets/svg/bookmark.svg
  src/pages/static/assets/svg/globe.svg
  src/pages/static/js/bookmarks.js
  src/pages/theme/bookmarks.css
  src/renderer.js
  src/window-manager.js
Labels: enhancement, UI/UX

#52 feat: Add P2P Apps Page, About/Version Placeholders, and Peersky Favicon Support
  docs/P2P.md
  docs/README.md
  src/pages/404.html
  src/pages/about.html
  src/pages/bookmarks.html
  src/pages/home.html
  src/pages/p2p/chat/index.html
  src/pages/p2p/editor/index.html
  src/pages/p2p/index.html
  src/pages/p2p/p2p-list.js
  src/pages/p2p/upload/index.html
  src/pages/plan1.html
  src/pages/static/assets/favicon.ico
  src/pages/version.html
  src/protocols/peersky-protocol.js
  src/renderer.js
Labels: documentation, enhancement
